language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
  - "9"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn add @babel/core @babel/cli @babel/plugin-proposal-class-properties
    @babel/plugin-proposal-export-default-from @babel/plugin-proposal-export-namespace-from
    @babel/plugin-proposal-object-rest-spread @babel/plugin-syntax-dynamic-import
    @babel/plugin-transform-template-literals @babel/plugin-proposal-function-bind
    @babel/plugin-transform-runtime @babel/runtime @babel/register regenerator-runtime
    babel-loader babel-core@7.0.0-bridge.0 jest babel-jest enzyme enzyme-adapter-react-16
    react-test-renderer semantic-release@next semantic-release-cli travis-deploy-once
    @semantic-release/git -D
  - yarn add react react-dom
script:
  - yarn run test
  - yarn run build
after_success:
  - yarn run semantic-release
